"use server";
import { createHash, randomBytes } from "node:crypto";
import { redirect } from "next/navigation";
import { db } from "@/server/db/client";
import { hashPassword } from "@/server/auth/password";
import { forgotPasswordSchema, registrationSchema, resetPasswordSchema } from "@/server/validators/auth";
import { DevelopmentEmailService } from "@/server/email";
import { getServerEnv } from "@/server/env";

export type AuthActionState={message?:string;errors?:Record<string,string[]>};
const fieldErrors=(error:{flatten:()=>{fieldErrors:Record<string,string[]>}})=>error.flatten().fieldErrors;
export async function registerAction(_:AuthActionState,formData:FormData):Promise<AuthActionState>{const parsed=registrationSchema.safeParse({firstName:formData.get("firstName"),lastName:formData.get("lastName"),email:formData.get("email"),phone:formData.get("phone")||undefined,password:formData.get("password"),passwordConfirmation:formData.get("passwordConfirmation"),acceptTerms:formData.get("acceptTerms")==="on"});if(!parsed.success)return{errors:fieldErrors(parsed.error)};const exists=await db.user.findUnique({where:{email:parsed.data.email},select:{id:true}});if(exists)return{message:"Unable to create this account. Try signing in or recovering your password."};const passwordHash=await hashPassword(parsed.data.password);await db.user.create({data:{email:parsed.data.email,passwordHash,firstName:parsed.data.firstName,lastName:parsed.data.lastName,phone:parsed.data.phone,status:"active",roles:{create:{role:"buyer"}},buyerProfile:{create:{}},wishlist:{create:{}},notificationPreference:{create:{}}}});redirect("/auth/sign-in?registered=1")}
export async function forgotPasswordAction(_:AuthActionState,formData:FormData):Promise<AuthActionState>{const parsed=forgotPasswordSchema.safeParse({email:formData.get("email")});const response={message:"If an account matches that email, password-reset instructions will be sent."};if(!parsed.success)return response;const user=await db.user.findUnique({where:{email:parsed.data.email},select:{id:true,email:true}});if(!user)return response;const token=randomBytes(32).toString("hex");const tokenHash=createHash("sha256").update(token).digest("hex");await db.passwordResetToken.create({data:{userId:user.id,tokenHash,expires:new Date(Date.now()+30*60*1000)}});await new DevelopmentEmailService().sendPasswordReset(user.email,`${getServerEnv().NEXT_PUBLIC_APP_URL}/auth/reset-password?token=${token}`);return response}
export async function resetPasswordAction(_:AuthActionState,formData:FormData):Promise<AuthActionState>{const parsed=resetPasswordSchema.safeParse({token:formData.get("token"),password:formData.get("password"),passwordConfirmation:formData.get("passwordConfirmation")});if(!parsed.success)return{errors:fieldErrors(parsed.error)};const tokenHash=createHash("sha256").update(parsed.data.token).digest("hex");const record=await db.passwordResetToken.findUnique({where:{tokenHash}});if(!record||record.usedAt||record.expires<new Date())return{message:"This reset link is invalid or expired."};await db.$transaction([db.user.update({where:{id:record.userId},data:{passwordHash:await hashPassword(parsed.data.password)}}),db.passwordResetToken.update({where:{tokenHash},data:{usedAt:new Date()}}),db.securityEvent.create({data:{userId:record.userId,type:"password_reset"}})]);redirect("/auth/sign-in?reset=1")}
