"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { BadgeCheck, ChevronRight, Heart, Minus, Plus, ShieldCheck, ShoppingBag, Trash2, Truck } from "lucide-react";
import { allProducts, getProductsBySellerId, getSellerById } from "@/data/mock/marketplace";
import { formatCurrency, getCartItemsBySeller, getCartSubtotal, getCartTotals, resolveCartItems } from "@/lib/marketplace";
import { useMarketplaceStore } from "@/stores/marketplace-store";
import type { Product, Seller } from "@/types/marketplace";
import { ProductCard } from "./ProductCard";

export function ProductExperience({ product }: { product: Product }) {
  const router=useRouter(); const [quantity,setQuantity]=useState(1);
  const add=useMarketplaceStore((state)=>state.addToCart); const beginBuyNow=useMarketplaceStore((state)=>state.beginBuyNow);
  const inCart=useMarketplaceStore((state)=>Boolean(state.cart[product.id])); const wished=useMarketplaceStore((state)=>state.wishlist.includes(product.id)); const toggle=useMarketplaceStore((state)=>state.toggleWishlist);
  const seller=getSellerById(product.sellerId); const discount=product.oldPrice?Math.round((1-product.price/product.oldPrice)*100):0;
  const buyNow=()=>{beginBuyNow({productId:product.id,quantity});router.push("/checkout");};
  return <main className="commerce-page product-page">
    <nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><ChevronRight/><Link href={`/category/${product.categorySlug}`}>{product.category}</Link><ChevronRight/><span>{product.name}</span></nav>
    <section className="product-detail">
      <div className="gallery"><div className="gallery-thumbs">{["Front","Side","Detail","In use"].map((label,index)=><button key={label} aria-label={`View ${label.toLowerCase()} image`} className={index===0?"active":""}>{product.emoji}</button>)}</div><div className="gallery-main" role="img" aria-label={product.name}>{product.emoji}<span>Verified product imagery</span></div></div>
      <div className="product-info"><span className="eyebrow">{product.brand}</span><h1>{product.name}</h1><div className="product-meta"><b>★ {product.rating}</b><span>{product.reviewCount?.toLocaleString()} reviews</span><span>{product.sold?.toLocaleString()} sold</span></div>{seller&&<Link className="seller-inline" href={`/store/${seller.slug}`}><BadgeCheck/> Sold by {seller.name}</Link>}<div className="detail-price"><strong>{formatCurrency(Math.round(product.price*100))}</strong>{product.oldPrice&&<><del>{formatCurrency(Math.round(product.oldPrice*100))}</del><span>-{discount}%</span></>}</div><p className="stock-line"><b>{product.status}</b> · {product.stock} available</p>
        <fieldset><legend>Colour</legend><div className="swatches"><button aria-label="Charcoal" className="selected"/><button aria-label="Orange"/><button aria-label="Cream"/></div></fieldset>
        <fieldset><legend>Package</legend><div className="choice-row"><button className="selected">Standard</button><button>With protection plan</button></div></fieldset>
        <div className="quantity"><span>Quantity</span><button aria-label="Decrease quantity" onClick={()=>setQuantity((value)=>Math.max(1,value-1))}><Minus/></button><b>{quantity}</b><button aria-label="Increase quantity" onClick={()=>setQuantity((value)=>Math.min(product.stock,value+1))}><Plus/></button></div>
        <div className="purchase-actions"><button className="button" disabled={product.stock===0} onClick={()=>add(product.id,quantity)}><ShoppingBag/> {inCart?"Add another":"Add to cart"}</button><button className="button secondary" disabled={product.stock===0} onClick={buyNow}>Buy now</button><button className="icon-button" aria-label={`${wished?"Remove from":"Add to"} wishlist`} aria-pressed={wished} onClick={()=>toggle(product.id)}><Heart fill={wished?"currentColor":"none"}/></button></div>
        <div className="delivery-cards"><div><Truck/><b>{product.delivery}</b><span>Estimated July 18–21 · ships from {product.supplierCountry}</span></div><div><ShieldCheck/><b>Weivas Pay & Buyer Protection</b><span>Secure checkout demonstration · eligible 30-day returns</span></div></div>
      </div>
      {seller&&<aside className="seller-panel"><div className="seller-avatar">{seller.logo}</div><small>VERIFIED SELLER</small><h2>{seller.name}</h2><p>{seller.rating} rating · {seller.feedback}% positive feedback</p><dl><div><dt>Response</dt><dd>{seller.responseRate}%</dd></div><div><dt>Orders</dt><dd>{seller.completedOrders.toLocaleString()}</dd></div></dl><Link className="button secondary" href={`/store/${seller.slug}`}>Visit store</Link><button className="button secondary">Contact seller</button></aside>}
    </section>
    <section className="detail-tabs"><div role="tablist"><button role="tab" aria-selected="true">Description</button><button role="tab">Specifications</button><button role="tab">Reviews ({product.reviewCount})</button><button role="tab">Questions & answers</button></div><article><h2>Designed for dependable everyday use</h2><p>{product.name} combines considered materials, verified seller support and practical performance. Product information shown here is demonstration content for the current frontend experience.</p><div className="spec-grid"><span><b>Brand</b>{product.brand}</span><span><b>SKU</b>{product.sku}</span><span><b>Warranty</b>{product.warranty||"Standard seller warranty"}</span><span><b>Returns</b>30-day eligible returns</span></div></article></section>
    <section className="section related"><div className="section-title"><div><span>YOU MAY ALSO LIKE</span><h2>Related products</h2></div></div><div className="product-grid">{allProducts.filter((item)=>item.id!==product.id).slice(0,6).map((item)=><ProductCard key={item.id} product={item}/>)}</div></section>
    <div className="mobile-purchase"><div><small>From</small><b>{formatCurrency(Math.round(product.price*100))}</b></div><button className="button" disabled={product.stock===0} onClick={()=>add(product.id,quantity)}>Add to cart</button></div>
  </main>;
}

export function StoreExperience({seller}:{seller:Seller}) {
  const sellerProducts=getProductsBySellerId(seller.id);
  return <main className="commerce-page store-page"><section className="store-hero"><div className="store-pattern"/><div className="store-identity"><div className="store-logo">{seller.logo}</div><div><small>VERIFIED WEIVAS STOREFRONT</small><h1>{seller.name}</h1><p><BadgeCheck/> Verified seller · {seller.country} · {seller.yearsActive} years on Weivas</p></div><div className="store-actions"><button className="button">Follow store</button><button className="button secondary">Contact seller</button></div></div><div className="store-stats">{[[seller.rating,"Rating"],[`${seller.responseRate}%`,"Response rate"],[seller.followers?.toLocaleString(),"Followers"],[seller.completedOrders.toLocaleString(),"Transactions"]].map(([value,label])=><span key={label}><b>{value}</b><small>{label}</small></span>)}</div></section><nav className="store-nav"><a href="#products">All products</a><a href="#promotions">Promotions</a><a href="#reviews">Reviews</a><a href="#policies">Policies</a></nav><section className="store-promo" id="promotions"><div><small>STORE-WIDE OFFER</small><h2>Products selected for work, life and everything between.</h2><p>Save on selected verified products this week.</p><Link className="button" href="#products">Shop the offer</Link></div><div>{seller.featured.join("  ")}</div></section><section className="section" id="products"><div className="section-title"><div><span>FROM THIS SELLER</span><h2>Featured products</h2></div></div><div className="product-grid">{sellerProducts.map((product)=><ProductCard key={product.id} product={product}/>)}</div></section><section className="store-lower"><article id="reviews"><small>SELLER REVIEWS</small><h2>{seller.rating} out of 5</h2><p>“Quick dispatch, careful packaging and exactly as described.”</p><b>{seller.feedback}% positive feedback from verified purchases</b></article><article id="policies"><small>STORE POLICIES</small><h2>Buy with clarity</h2><ul><li>Replies within one business day</li><li>30-day eligible returns</li><li>Tracking on every shipment</li><li>Weivas Buyer Protection applies</li></ul></article></section></main>;
}

function Summary({items,checkout=false,onCheckout}:{items:ReturnType<typeof resolveCartItems>;checkout?:boolean;onCheckout?:()=>void}) {
  const totals=getCartTotals(items);
  return <aside className="order-summary"><h2>Order summary</h2><dl><div><dt>Subtotal</dt><dd>{formatCurrency(totals.subtotalMinor)}</dd></div><div><dt>Discounts</dt><dd className="positive">−{formatCurrency(totals.discountMinor)}</dd></div><div><dt>Shipping</dt><dd>{totals.shippingMinor?formatCurrency(totals.shippingMinor):"Free"}</dd></div><div><dt>Estimated taxes</dt><dd>{formatCurrency(totals.taxMinor)}</dd></div><div className="total"><dt>Total</dt><dd>{formatCurrency(totals.totalMinor)}</dd></div></dl>{checkout?<button className="button">Place mock order</button>:<Link className="button" href="/checkout" onClick={onCheckout}>Proceed to checkout</Link>}<p><ShieldCheck/> Protected by Weivas Buyer Protection. No live payment will be taken.</p></aside>;
}

export function CartExperience() {
  const cart=useMarketplaceStore((state)=>state.cart); const setQuantity=useMarketplaceStore((state)=>state.setQuantity); const remove=useMarketplaceStore((state)=>state.removeFromCart); const beginCartCheckout=useMarketplaceStore((state)=>state.beginCartCheckout);
  const items=resolveCartItems(Object.entries(cart).map(([productId,quantity])=>({productId,quantity})),allProducts); const groups=getCartItemsBySeller(items);
  return <main className="commerce-page cart-page"><header className="page-heading"><span className="eyebrow">YOUR BASKET</span><h1>Cart</h1><p>Items are grouped by seller for clearer fulfilment.</p></header>{items.length===0?<section className="empty-state"><ShoppingBag/><h2>Your cart is empty</h2><p>Explore handpicked products from verified sellers.</p><Link className="button" href="/search">Continue shopping</Link></section>:<div className="cart-layout"><div>{[...groups].map(([sellerId,sellerItems])=>{const seller=getSellerById(sellerId);return <section className="seller-group" key={sellerId}><header><div><BadgeCheck/><b>{seller?.name}</b><small>Verified seller</small></div><span>Estimated delivery July 18–21</span></header>{sellerItems.map(({product,quantity,lineTotalMinor})=><article className="cart-item" key={product.id}><div className="cart-image">{product.emoji}</div><div><Link href={`/product/${product.slug}`}><h2>{product.name}</h2></Link><p>{product.brand} · {product.status}</p><button>Save for later</button><button onClick={()=>remove(product.id)}><Trash2/> Remove</button></div><div className="cart-item-end"><strong>{formatCurrency(lineTotalMinor)}</strong><div className="quantity"><button aria-label={`Decrease ${product.name}`} onClick={()=>setQuantity(product.id,quantity-1)}><Minus/></button><b>{quantity}</b><button aria-label={`Increase ${product.name}`} onClick={()=>setQuantity(product.id,quantity+1)}><Plus/></button></div></div></article>)}<footer><span>Seller subtotal</span><b>{formatCurrency(getCartSubtotal(sellerItems))}</b></footer></section>})}</div><Summary items={items} onCheckout={beginCartCheckout}/></div>}</main>;
}

export function CheckoutExperience() {
  const checkout=useMarketplaceStore((state)=>state.checkout); const items=resolveCartItems(checkout?.items??[],allProducts); const groups=getCartItemsBySeller(items);
  if(!checkout||items.length===0) return <main className="commerce-page checkout-page"><header className="page-heading"><span className="eyebrow">SECURE CHECKOUT DEMO</span><h1>Nothing to check out yet</h1><p>Add products to your cart or choose Buy Now on a product page.</p></header><section className="empty-state"><ShoppingBag/><h2>Your checkout is empty</h2><p>No products have been fabricated for this order.</p><Link className="button" href="/cart">Return to cart</Link></section></main>;
  return <main className="commerce-page checkout-page"><header className="page-heading"><span className="eyebrow">SECURE CHECKOUT DEMO</span><h1>Review and place your order</h1><p>{checkout.mode==="buy_now"?"Buy Now checkout":"Cart checkout"} · Payment and fulfilment remain mocked.</p></header><div className="checkout-layout"><div className="checkout-steps"><section><header><span>1</span><div><h2>Delivery address</h2><p>John Doe · 123 Market Street, Lagos, Nigeria</p></div><button>Edit</button></header></section>{[...groups].map(([sellerId,sellerItems],index)=>{const seller=getSellerById(sellerId);return <section key={sellerId}><header><span>{index+2}</span><div><h2>Shipment from {seller?.name}</h2><p>{sellerItems.reduce((sum,item)=>sum+item.quantity,0)} items · estimated July 18–21</p></div></header><label className="delivery-option"><input type="radio" name={`delivery-${sellerId}`} defaultChecked/><Truck/><span><b>Standard delivery</b><small>Tracked · calculated in summary</small></span></label>{sellerItems.map(({product,quantity,lineTotalMinor})=><div className="checkout-product" key={product.id}><span>{product.emoji}</span><b>{product.name} × {quantity}</b><strong>{formatCurrency(lineTotalMinor)}</strong></div>)}</section>})}<section><header><span>{groups.size+2}</span><div><h2>Payment method</h2><p>Frontend demonstration only</p></div></header><div className="mock-payment"><ShieldCheck/><div><b>Weivas Pay placeholder</b><p>No card data is collected and no payment will be processed.</p></div></div></section></div><Summary items={items} checkout/></div></main>;
}
