"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { BadgeCheck, ChevronRight, Heart, Minus, Plus, ShieldCheck, ShoppingBag, Trash2, Truck } from "lucide-react";
import { formatCurrency, getCartItemsBySeller, getCartSubtotal, getCartTotals, resolveCartItems } from "@/lib/marketplace";
import { useMarketplaceStore } from "@/stores/marketplace-store";
import type { Product, Seller } from "@/types/marketplace";
import { ProductCard } from "./ProductCard";
import { placeOrder } from "@/app/(marketplace)/checkout/actions";

export function ProductExperience({ product, relatedProducts=[] }: { product: Product; relatedProducts?: Product[] }) {
  const router=useRouter(); const [quantity,setQuantity]=useState(1);
  const add=useMarketplaceStore((state)=>state.addToCart); const beginBuyNow=useMarketplaceStore((state)=>state.beginBuyNow);const remember=useMarketplaceStore(state=>state.rememberProduct);useEffect(()=>remember(product),[product,remember]);
  const inCart=useMarketplaceStore((state)=>Boolean(state.cart[product.id])); const wished=useMarketplaceStore((state)=>state.wishlist.includes(product.id)); const toggle=useMarketplaceStore((state)=>state.toggleWishlist);
  const discount=product.oldPrice?Math.round((1-product.price/product.oldPrice)*100):0;
  const buyNow=()=>{beginBuyNow({productId:product.id,quantity});router.push("/checkout");};
  return <main className="commerce-page product-page">
    <nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><ChevronRight/><Link href={`/category/${product.categorySlug}`}>{product.category}</Link><ChevronRight/><span>{product.name}</span></nav>
    <section className="product-detail">
      <div className="gallery"><div className="gallery-thumbs"><button aria-label="View primary product image" className="active">{product.imageUrl?<span className="product-image" style={{backgroundImage:`url(${product.imageUrl})`}}/>:product.emoji}</button></div><div className="gallery-main" role="img" aria-label={product.imageAlt??product.name}>{product.imageUrl?<span className="product-image" style={{backgroundImage:`url(${product.imageUrl})`}}/>:product.emoji}<span>{product.imageUrl?"Seller-provided product image":"Image coming soon"}</span></div></div>
      <div className="product-info"><span className="eyebrow">{product.brand??product.category}</span><h1>{product.name}</h1><div className="product-meta">{product.reviewCount&&product.reviewCount>0?<><b>★ {product.rating}</b><span>{product.reviewCount.toLocaleString()} reviews</span></>:<span>No customer reviews yet</span>}</div>{product.sellerSlug&&product.sellerName&&<Link className="seller-inline" href={`/store/${product.sellerSlug}`}><BadgeCheck/> Sold by {product.sellerName}</Link>}<div className="detail-price"><strong>{formatCurrency(Math.round(product.price*100))}</strong>{product.oldPrice&&<><del>{formatCurrency(Math.round(product.oldPrice*100))}</del><span>-{discount}%</span></>}</div><p className="stock-line"><b>{product.status}</b> · {product.stock} available</p>
        <div className="quantity"><span>Quantity</span><button aria-label="Decrease quantity" onClick={()=>setQuantity((value)=>Math.max(1,value-1))}><Minus/></button><b>{quantity}</b><button aria-label="Increase quantity" onClick={()=>setQuantity((value)=>Math.min(product.stock,value+1))}><Plus/></button></div>
        <div className="purchase-actions"><button className="button" disabled={product.stock===0} onClick={()=>add(product.id,quantity)}><ShoppingBag/> {inCart?"Add another":"Add to cart"}</button><button className="button secondary" disabled={product.stock===0} onClick={buyNow}>Buy now</button><button className="icon-button" aria-label={`${wished?"Remove from":"Add to"} wishlist`} aria-pressed={wished} onClick={()=>toggle(product.id)}><Heart fill={wished?"currentColor":"none"}/></button></div>
        <div className="delivery-cards"><div><Truck/><b>{product.delivery}</b><span>Ships from {product.supplierCountry}; cost and timing are confirmed before payment.</span></div><div><ShieldCheck/><b>Order support</b><span>{product.returnPolicy??"Return eligibility is confirmed from the seller policy before purchase."}</span></div></div>
      </div>
      {product.sellerName&&<aside className="seller-panel"><div className="seller-avatar">W</div><small>{product.verified?"VERIFIED SELLER":"SELLER"}</small><h2>{product.sellerName}</h2><p>No public seller reviews yet.</p>{product.sellerSlug&&<Link className="button secondary" href={`/store/${product.sellerSlug}`}>Visit store</Link>}<Link className="button secondary" href="/support">Contact support</Link></aside>}
    </section>
    <section className="detail-tabs"><div role="tablist"><button role="tab" aria-selected="true">Description</button><button role="tab">Product information</button><button role="tab">Reviews ({product.reviewCount??0})</button></div><article><h2>Product description</h2><p>{product.description}</p><div className="spec-grid"><span><b>Brand</b>{product.brand??"Not specified"}</span><span><b>SKU</b>{product.sku}</span><span><b>Warranty</b>{product.warranty||"Not specified"}</span><span><b>Returns</b>{product.returnPolicy||"See seller policy"}</span></div></article></section>
    {relatedProducts.length>0&&<section className="section related"><div className="section-title"><div><span>YOU MAY ALSO LIKE</span><h2>Related products</h2></div></div><div className="product-grid">{relatedProducts.map((item)=><ProductCard key={item.id} product={item}/>)}</div></section>}
    <div className="mobile-purchase"><div><small>From</small><b>{formatCurrency(Math.round(product.price*100))}</b></div><button className="button" disabled={product.stock===0} onClick={()=>add(product.id,quantity)}>Add to cart</button></div>
  </main>;
}

export function StoreExperience({seller,products=[]}:{seller:Seller;products?:Product[]}) {
  const sellerProducts=products;
  return <main className="commerce-page store-page"><section className="store-hero"><div className="store-pattern"/><div className="store-identity"><div className="store-logo">{seller.logo}</div><div><small>{seller.verified?"VERIFIED WEIVAS STOREFRONT":"WEIVAS STOREFRONT"}</small><h1>{seller.name}</h1><p>{seller.verified&&<BadgeCheck/>} {seller.country}</p></div><div className="store-actions"><Link className="button secondary" href="/support">Contact support</Link></div></div></section><nav className="store-nav"><a href="#products">All products</a><a href="#reviews">Reviews</a><a href="#policies">Policies</a></nav><section className="section" id="products"><div className="section-title"><div><span>FROM THIS SELLER</span><h2>Products</h2></div></div>{sellerProducts.length?<div className="product-grid">{sellerProducts.map((product)=><ProductCard key={product.id} product={product}/>)}</div>:<div className="empty"><b>No active products yet.</b></div>}</section><section className="store-lower"><article id="reviews"><small>SELLER REVIEWS</small><h2>No customer reviews yet</h2><p>Verified-purchase feedback will appear here after completed orders.</p></article><article id="policies"><small>STORE POLICIES</small><h2>Buy with clarity</h2><p>Product-specific warranty, delivery and return information is shown on each listing.</p></article></section></main>;
}

function Summary({items,checkout=false,checkoutEnabled=false,onCheckout,addresses=[]}:{items:ReturnType<typeof resolveCartItems>;checkout?:boolean;checkoutEnabled?:boolean;onCheckout?:()=>void;addresses?:{id:string;label:string;summary:string}[]}) {
  const totals=getCartTotals(items);
  return <aside className="order-summary"><h2>Order summary</h2><dl><div><dt>Product subtotal</dt><dd>{formatCurrency(totals.subtotalMinor)}</dd></div><div><dt>Discounts</dt><dd>None applied</dd></div><div><dt>Delivery</dt><dd>Not yet calculated</dd></div><div><dt>Tax</dt><dd>Not yet calculated</dd></div><div className="total"><dt>Current total</dt><dd>{formatCurrency(totals.totalMinor)}</dd></div></dl>{checkout?<form action={placeOrder}><input type="hidden" name="items" value={JSON.stringify(items.map(({product,quantity})=>({productId:product.id,quantity})))}/><label>Delivery address<select name="addressId" required defaultValue={addresses[0]?.id}>{addresses.map(address=><option key={address.id} value={address.id}>{address.label}: {address.summary}</option>)}</select></label>{!addresses.length?<Link className="button" href="/account/addresses">Add a delivery address</Link>:checkoutEnabled?<button className="button" type="submit">Continue to payment</button>:<button className="button" type="button" disabled>Online checkout is not active yet</button>}</form>:<Link className="button" href="/checkout" onClick={onCheckout}>Proceed to checkout</Link>}<p><ShieldCheck/> Final delivery, tax and payment totals must be confirmed before an order is accepted.</p></aside>;
}

export function CartExperience({persistedItems,persistedProducts=[]}:{persistedItems?:import("@/types/marketplace").CartItem[];persistedProducts?:Product[]}) {
  const hydrate=useMarketplaceStore(state=>state.hydrateCart);useEffect(()=>{if(persistedItems)hydrate(persistedItems,persistedProducts)},[hydrate,persistedItems,persistedProducts]);
  const cart=useMarketplaceStore((state)=>state.cart);const catalog=useMarketplaceStore(state=>state.catalog); const setQuantity=useMarketplaceStore((state)=>state.setQuantity); const remove=useMarketplaceStore((state)=>state.removeFromCart); const beginCartCheckout=useMarketplaceStore((state)=>state.beginCartCheckout);
  const items=resolveCartItems(Object.entries(cart).map(([productId,quantity])=>({productId,quantity})),Object.values(catalog)); const groups=getCartItemsBySeller(items);
  return <main className="commerce-page cart-page"><header className="page-heading"><span className="eyebrow">YOUR BASKET</span><h1>Cart</h1><p>Items are grouped by seller for clearer fulfilment.</p></header>{items.length===0?<section className="empty-state"><ShoppingBag/><h2>Your cart is empty</h2><p>Explore approved products from active sellers.</p><Link className="button" href="/search">Continue shopping</Link></section>:<div className="cart-layout"><div>{[...groups].map(([sellerId,sellerItems])=><section className="seller-group" key={sellerId}><header><div><BadgeCheck/><b>{sellerItems[0]?.product.sellerName}</b><small>{sellerItems[0]?.product.verified?"Verified seller":"Seller"}</small></div><span>Delivery confirmed at checkout</span></header>{sellerItems.map(({product,quantity,lineTotalMinor})=><article className="cart-item" key={product.id}><div className="cart-image">{product.emoji}</div><div><Link href={`/product/${product.slug}`}><h2>{product.name}</h2></Link><p>{product.brand??product.category} · {product.status}</p><button onClick={()=>remove(product.id)}><Trash2/> Remove</button></div><div className="cart-item-end"><strong>{formatCurrency(lineTotalMinor)}</strong><div className="quantity"><button aria-label={`Decrease ${product.name}`} onClick={()=>setQuantity(product.id,quantity-1)}><Minus/></button><b>{quantity}</b><button aria-label={`Increase ${product.name}`} onClick={()=>setQuantity(product.id,quantity+1)}><Plus/></button></div></div></article>)}<footer><span>Seller subtotal</span><b>{formatCurrency(getCartSubtotal(sellerItems))}</b></footer></section>)}</div><Summary items={items} onCheckout={beginCartCheckout}/></div>}</main>;
}

export function CheckoutExperience({addresses=[],checkoutEnabled=false}:{addresses?:{id:string;label:string;summary:string}[];checkoutEnabled?:boolean}) {
  const checkout=useMarketplaceStore((state)=>state.checkout);const catalog=useMarketplaceStore(state=>state.catalog); const items=resolveCartItems(checkout?.items??[],Object.values(catalog)); const groups=getCartItemsBySeller(items);
  if(!checkout||items.length===0) return <main className="commerce-page checkout-page"><header className="page-heading"><span className="eyebrow">SECURE CHECKOUT DEMO</span><h1>Nothing to check out yet</h1><p>Add products to your cart or choose Buy Now on a product page.</p></header><section className="empty-state"><ShoppingBag/><h2>Your checkout is empty</h2><p>No products have been fabricated for this order.</p><Link className="button" href="/cart">Return to cart</Link></section></main>;
  return <main className="commerce-page checkout-page"><header className="page-heading"><span className="eyebrow">CHECKOUT</span><h1>Review your order</h1><p>{checkout.mode==="buy_now"?"Buy Now checkout":"Cart checkout"} · Prices and stock are verified by the server.</p></header><div className="checkout-layout"><div className="checkout-steps"><section><header><span>1</span><div><h2>Delivery address</h2><p>{addresses[0]?.summary??"Add a delivery address to continue."}</p></div><Link href="/account/addresses">Edit</Link></header></section>{[...groups].map(([sellerId,sellerItems],index)=>{const sellerName=sellerItems[0]?.product.sellerName??"Seller";return <section key={sellerId}><header><span>{index+2}</span><div><h2>Shipment from {sellerName}</h2><p>{sellerItems.reduce((sum,item)=>sum+item.quantity,0)} items · delivery cost and timing are not yet confirmed</p></div></header>{sellerItems.map(({product,quantity,lineTotalMinor})=><div className="checkout-product" key={product.id}><span>{product.emoji}</span><b>{product.name} × {quantity}</b><strong>{formatCurrency(lineTotalMinor)}</strong></div>)}</section>})}<section><header><span>{groups.size+2}</span><div><h2>Payment</h2><p>{checkoutEnabled?"Configured provider will open after final total validation":"Online payment is not active yet"}</p></div></header><div className="mock-payment"><ShieldCheck/><div><b>{checkoutEnabled?"Provider configured":"Checkout activation pending"}</b><p>No card or bank details are collected by WEIVAS directly.</p></div></div></section></div><Summary items={items} checkout checkoutEnabled={checkoutEnabled} addresses={addresses}/></div></main>;
}
