"use server";
import { randomBytes } from "node:crypto";
import { redirect } from "next/navigation";
import { z } from "zod";
import { requireArea } from "@/server/auth/session";
import { db } from "@/server/db/client";
import { createOrderDraft } from "@/server/services/orders/draft";

const itemsSchema=z.array(z.object({productId:z.string().min(1),quantity:z.number().int().min(1).max(100)})).min(1).max(100);
export async function placeOrder(formData:FormData){const session=await requireArea("account");const items=itemsSchema.parse(JSON.parse(String(formData.get("items")||"[]")));const address=await db.address.findFirst({where:{id:String(formData.get("addressId")),userId:session.user.id}});if(!address)throw new Error("Choose a valid delivery address.");const products=await db.product.findMany({where:{id:{in:items.map(item=>item.productId)},status:"active",store:{status:"active"}},include:{store:true}});if(products.length!==new Set(items.map(item=>item.productId)).size)throw new Error("One or more products are no longer available.");const lines=items.map(item=>{const product=products.find(candidate=>candidate.id===item.productId)!;return{productId:product.id,sellerProfileId:product.sellerProfileId,storeId:product.storeId,title:product.title,sku:product.sku,unitPriceMinor:product.priceMinor,quantity:item.quantity,stock:product.stock,available:product.stock>=item.quantity}});const draft=createOrderDraft({buyerId:session.user.id,currency:"USD",addressId:address.id,lines});const orderNumber=`WIV-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${randomBytes(4).toString("hex").toUpperCase()}`;const order=await db.$transaction(async tx=>{for(const line of lines){const updated=await tx.product.updateMany({where:{id:line.productId,stock:{gte:line.quantity},status:"active"},data:{stock:{decrement:line.quantity}}});if(updated.count!==1)throw new Error(`${line.title} no longer has enough stock.`)}const created=await tx.order.create({data:{orderNumber,buyerId:session.user.id,currency:"USD",subtotalMinor:draft.subtotalMinor,discountMinor:0,shippingMinor:0,taxMinor:0,totalMinor:draft.totalMinor,status:"pending_payment",addresses:{create:{type:"shipping",firstName:address.firstName,lastName:address.lastName,phone:address.phone,line1:address.line1,line2:address.line2,city:address.city,stateRegion:address.stateRegion,postalCode:address.postalCode,countryCode:address.countryCode}},sellerOrders:{create:draft.sellerOrders.map(sellerOrder=>({sellerProfileId:sellerOrder.sellerProfileId,storeId:sellerOrder.storeId,subtotalMinor:sellerOrder.subtotalMinor,shippingMinor:0,taxMinor:0,totalMinor:sellerOrder.subtotalMinor,status:"pending_payment",items:{create:sellerOrder.items}}))}}});const cart=await tx.cart.findUnique({where:{userId:session.user.id}});if(cart)await tx.cartItem.deleteMany({where:{cartId:cart.id,productId:{in:items.map(item=>item.productId)}}});return created});redirect(`/account/orders/${order.id}`)}
