"use server";
import { revalidatePath } from "next/cache";import { db } from "@/server/db/client";import { requireArea } from "@/server/auth/session";import { addressSchema,profileSchema } from "@/server/validators/account";
import { changePasswordSchema } from "@/server/validators/auth";import { hashPassword,verifyPassword } from "@/server/auth/password";
export async function saveAddress(formData:FormData){const session=await requireArea("account");const parsed=addressSchema.parse({label:formData.get("label"),firstName:formData.get("firstName"),lastName:formData.get("lastName"),phone:formData.get("phone"),line1:formData.get("line1"),line2:formData.get("line2")||undefined,city:formData.get("city"),stateRegion:formData.get("stateRegion"),postalCode:formData.get("postalCode"),countryCode:String(formData.get("countryCode")||"").toUpperCase(),isDefaultShipping:formData.get("isDefaultShipping")==="on",isDefaultBilling:formData.get("isDefaultBilling")==="on"});const id=String(formData.get("id")||"");await db.$transaction(async(tx)=>{if(parsed.isDefaultShipping)await tx.address.updateMany({where:{userId:session.user.id},data:{isDefaultShipping:false}});if(parsed.isDefaultBilling)await tx.address.updateMany({where:{userId:session.user.id},data:{isDefaultBilling:false}});if(id)await tx.address.update({where:{id,userId:session.user.id},data:parsed});else await tx.address.create({data:{...parsed,userId:session.user.id}})});revalidatePath("/account/addresses")}
export async function deleteAddress(formData:FormData){const session=await requireArea("account");await db.address.delete({where:{id:String(formData.get("id")),userId:session.user.id}});revalidatePath("/account/addresses")}
export async function updateProfile(formData:FormData){const session=await requireArea("account");const parsed=profileSchema.parse({firstName:formData.get("firstName"),lastName:formData.get("lastName"),phone:formData.get("phone")||undefined,preferredCurrency:formData.get("preferredCurrency"),preferredLanguage:formData.get("preferredLanguage")});await db.$transaction([db.user.update({where:{id:session.user.id},data:{firstName:parsed.firstName,lastName:parsed.lastName,phone:parsed.phone}}),db.buyerProfile.upsert({where:{userId:session.user.id},create:{userId:session.user.id,preferredCurrency:parsed.preferredCurrency,preferredLanguage:parsed.preferredLanguage},update:{preferredCurrency:parsed.preferredCurrency,preferredLanguage:parsed.preferredLanguage}})]);revalidatePath("/account/settings")}
export async function removeWishlistItem(formData:FormData){const session=await requireArea("account");const wishlist=await db.wishlist.findUnique({where:{userId:session.user.id},select:{id:true}});if(wishlist)await db.wishlistItem.deleteMany({where:{wishlistId:wishlist.id,productId:String(formData.get("productId"))}});revalidatePath("/account/wishlist")}
export async function updateNotifications(formData:FormData){const session=await requireArea("account");const data={emailOrders:formData.get("emailOrders")==="on",emailPromotions:formData.get("emailPromotions")==="on",emailSecurity:formData.get("emailSecurity")==="on",pushOrders:formData.get("pushOrders")==="on",pushPromotions:formData.get("pushPromotions")==="on"};await db.notificationPreference.upsert({where:{userId:session.user.id},create:{userId:session.user.id,...data},update:data});revalidatePath("/account/notifications")}
export async function changePassword(formData:FormData){const session=await requireArea("account");const parsed=changePasswordSchema.parse({currentPassword:formData.get("currentPassword"),password:formData.get("password"),passwordConfirmation:formData.get("passwordConfirmation")});const user=await db.user.findUniqueOrThrow({where:{id:session.user.id},select:{passwordHash:true}});if(!await verifyPassword(parsed.currentPassword,user.passwordHash))throw new Error("Current password is incorrect.");await db.$transaction([db.user.update({where:{id:session.user.id},data:{passwordHash:await hashPassword(parsed.password)}}),db.securityEvent.create({data:{userId:session.user.id,type:"password_changed"}})]);revalidatePath("/account/security")}
