"use client";
import { useActionState, useState } from "react";
import Link from "next/link";
import { signIn } from "next-auth/react";
import { forgotPasswordAction, registerAction, resetPasswordAction, type AuthActionState } from "@/app/auth/actions";
const initial:AuthActionState={};
function ErrorText({errors,name}:{errors?:Record<string,string[]>;name:string}){return errors?.[name]?.[0]?<small className="field-error" id={`${name}-error`}>{errors[name][0]}</small>:null}
const Field=({label,name,type="text",errors,defaultValue}:{label:string;name:string;type?:string;errors?:Record<string,string[]>;defaultValue?:string})=><label>{label}<input name={name} type={type} defaultValue={defaultValue} aria-invalid={Boolean(errors?.[name])} aria-describedby={errors?.[name]?`${name}-error`:undefined} required/><ErrorText errors={errors} name={name}/></label>;
export function RegisterForm(){const [state,action,pending]=useActionState(registerAction,initial);return <form action={action} className="auth-form"><div className="form-grid"><Field label="First name" name="firstName" errors={state.errors}/><Field label="Last name" name="lastName" errors={state.errors}/></div><Field label="Email" name="email" type="email" errors={state.errors}/><Field label="Phone (optional)" name="phone" type="tel" errors={state.errors}/><Field label="Password" name="password" type="password" errors={state.errors}/><Field label="Confirm password" name="passwordConfirmation" type="password" errors={state.errors}/><label className="check"><input name="acceptTerms" type="checkbox"/> I accept the Weivas terms and privacy notice.</label><ErrorText errors={state.errors} name="acceptTerms"/>{state.message&&<p role="alert" className="form-message">{state.message}</p>}<button className="button" disabled={pending}>{pending?"Creating account…":"Create buyer account"}</button></form>}
export function SignInForm({callbackUrl="/account"}:{callbackUrl?:string}){const [message,setMessage]=useState("");const [pending,setPending]=useState(false);return <form className="auth-form" onSubmit={async(event)=>{event.preventDefault();setPending(true);const data=new FormData(event.currentTarget);const result=await signIn("credentials",{email:data.get("email"),password:data.get("password"),callbackUrl,redirect:false});setPending(false);if(result?.ok)window.location.assign(result.url??callbackUrl);else setMessage("Invalid email or password.")}}><Field label="Email" name="email" type="email"/><Field label="Password" name="password" type="password"/>{message&&<p role="alert" className="form-message">{message}</p>}<button className="button" disabled={pending}>{pending?"Signing in…":"Sign in securely"}</button><Link href="/auth/forgot-password">Forgot password?</Link></form>}
export function ForgotPasswordForm(){const [state,action,pending]=useActionState(forgotPasswordAction,initial);return <form action={action} className="auth-form"><Field label="Email" name="email" type="email" errors={state.errors}/>{state.message&&<p role="status" className="form-message">{state.message}</p>}<button className="button" disabled={pending}>Send recovery instructions</button></form>}
export function ResetPasswordForm({token}:{token:string}){const [state,action,pending]=useActionState(resetPasswordAction,initial);return <form action={action} className="auth-form"><input type="hidden" name="token" value={token}/><Field label="New password" name="password" type="password" errors={state.errors}/><Field label="Confirm new password" name="passwordConfirmation" type="password" errors={state.errors}/>{state.message&&<p role="alert" className="form-message">{state.message}</p>}<button className="button" disabled={pending}>Reset password</button></form>}
